// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  accuserSeat: __t.u8().name("accuser_seat"),
  accusedSeat: __t.u8().name("accused_seat"),
  timestamp: __t.timestamp(),
  accusedDecisionId: __t.option(__t.u64()).name("accused_decision_id"),
  accusedCommunicationId: __t.option(__t.u64()).name("accused_communication_id"),
  confidence: __t.u8(),
  reasoningZstd: __t.byteArray().name("reasoning_zstd"),
});
