// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  handId: __t.u64().name("hand_id"),
  seat: __t.u8(),
  timestamp: __t.timestamp(),
  phase: __t.u8(),
  audience: __t.u8(),
  targetSeat: __t.option(__t.u8()).name("target_seat"),
  textZstd: __t.byteArray().name("text_zstd"),
  referencedCard: __t.option(__t.u8()).name("referenced_card"),
  selfReportedCheat: __t.u8().name("self_reported_cheat"),
  engineDetectedLie: __t.bool().name("engine_detected_lie"),
});
