// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  schemaVersion: __t.u8().name("schema_version"),
  tournamentId: __t.option(__t.u64()).name("tournament_id"),
  startedAt: __t.timestamp().name("started_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  targetScore: __t.u16().name("target_score"),
  variant: __t.u8(),
  team1Seat0ModelId: __t.u32().name("team_1_seat_0_model_id"),
  team1Seat2ModelId: __t.u32().name("team_1_seat_2_model_id"),
  team2Seat1ModelId: __t.u32().name("team_2_seat_1_model_id"),
  team2Seat3ModelId: __t.u32().name("team_2_seat_3_model_id"),
  team1Score: __t.i16().name("team_1_score"),
  team2Score: __t.i16().name("team_2_score"),
  team1Bags: __t.u8().name("team_1_bags"),
  team2Bags: __t.u8().name("team_2_bags"),
  winnerTeam: __t.u8().name("winner_team"),
  rngSeed: __t.u64().name("rng_seed"),
  allowRenege: __t.bool().name("allow_renege"),
  chatPolicy: __t.u8().name("chat_policy"),
  promptCheatingMode: __t.u8().name("prompt_cheating_mode"),
  promptForDetection: __t.bool().name("prompt_for_detection"),
  announceDetectedCheats: __t.bool().name("announce_detected_cheats"),
  agentDetectionQuorum: __t.bool().name("agent_detection_quorum"),
  cheatConsequenceKind: __t.u8().name("cheat_consequence_kind"),
  cheatConsequenceValue: __t.i16().name("cheat_consequence_value"),
  spadesLeadPolicy: __t.u8().name("spades_lead_policy"),
  minimumTeamBid: __t.u8().name("minimum_team_bid"),
});
