// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  gameId: __t.u64().name("game_id"),
  handNumber: __t.u8().name("hand_number"),
  dealerSeat: __t.u8().name("dealer_seat"),
  dealSeat0: __t.u64().name("deal_seat_0"),
  dealSeat1: __t.u64().name("deal_seat_1"),
  dealSeat2: __t.u64().name("deal_seat_2"),
  dealSeat3: __t.u64().name("deal_seat_3"),
  bidsPacked: __t.u32().name("bids_packed"),
  tricksWonPacked: __t.u16().name("tricks_won_packed"),
  team1ScoreDelta: __t.i16().name("team_1_score_delta"),
  team2ScoreDelta: __t.i16().name("team_2_score_delta"),
});
