// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Accusation = __t.object("Accusation", {
  id: __t.u64(),
  gameId: __t.u64(),
  accuserSeat: __t.u8(),
  accusedSeat: __t.u8(),
  timestamp: __t.timestamp(),
  accusedDecisionId: __t.option(__t.u64()),
  accusedCommunicationId: __t.option(__t.u64()),
  confidence: __t.u8(),
  reasoningZstd: __t.byteArray(),
});
export type Accusation = __Infer<typeof Accusation>;

export const AccusationInput = __t.object("AccusationInput", {
  gameId: __t.u64(),
  accuserSeat: __t.u8(),
  accusedSeat: __t.u8(),
  accusedDecisionId: __t.option(__t.u64()),
  accusedCommunicationId: __t.option(__t.u64()),
  confidence: __t.u8(),
  reasoningZstd: __t.byteArray(),
});
export type AccusationInput = __Infer<typeof AccusationInput>;

export const Communication = __t.object("Communication", {
  id: __t.u64(),
  gameId: __t.u64(),
  handId: __t.u64(),
  seat: __t.u8(),
  timestamp: __t.timestamp(),
  phase: __t.u8(),
  audience: __t.u8(),
  targetSeat: __t.option(__t.u8()),
  textZstd: __t.byteArray(),
  referencedCard: __t.option(__t.u8()),
  selfReportedCheat: __t.u8(),
  engineDetectedLie: __t.bool(),
});
export type Communication = __Infer<typeof Communication>;

export const CommunicationInput = __t.object("CommunicationInput", {
  gameId: __t.u64(),
  handId: __t.u64(),
  seat: __t.u8(),
  phase: __t.u8(),
  audience: __t.u8(),
  targetSeat: __t.option(__t.u8()),
  textZstd: __t.byteArray(),
  referencedCard: __t.option(__t.u8()),
  selfReportedCheat: __t.u8(),
  engineDetectedLie: __t.bool(),
});
export type CommunicationInput = __Infer<typeof CommunicationInput>;

export const CompletedGameInput = __t.object("CompletedGameInput", {
  schemaVersion: __t.u8(),
  tournamentId: __t.option(__t.u64()),
  targetScore: __t.u16(),
  variant: __t.u8(),
  team1Seat0ModelId: __t.u32(),
  team1Seat2ModelId: __t.u32(),
  team2Seat1ModelId: __t.u32(),
  team2Seat3ModelId: __t.u32(),
  team1Score: __t.i16(),
  team2Score: __t.i16(),
  team1Bags: __t.u8(),
  team2Bags: __t.u8(),
  winnerTeam: __t.u8(),
  rngSeed: __t.u64(),
  allowRenege: __t.bool(),
  chatPolicy: __t.u8(),
  promptCheatingMode: __t.u8(),
  promptForDetection: __t.bool(),
  announceDetectedCheats: __t.bool(),
  agentDetectionQuorum: __t.bool(),
  cheatConsequenceKind: __t.u8(),
  cheatConsequenceValue: __t.i16(),
  spadesLeadPolicy: __t.u8(),
  minimumTeamBid: __t.u8(),
});
export type CompletedGameInput = __Infer<typeof CompletedGameInput>;

export const Decision = __t.object("Decision", {
  id: __t.u64(),
  gameId: __t.u64(),
  handId: __t.u64(),
  modelId: __t.u32(),
  decisionIndex: __t.u16(),
  seat: __t.u8(),
  kind: __t.u8(),
  action: __t.u8(),
  legalMask: __t.u64(),
  fingerprint: __t.u64(),
  latencyMs: __t.u16(),
  engineCheatKind: __t.u8(),
  selfReportedCheat: __t.u8(),
});
export type Decision = __Infer<typeof Decision>;

export const DecisionInput = __t.object("DecisionInput", {
  gameId: __t.u64(),
  handId: __t.u64(),
  modelId: __t.u32(),
  decisionIndex: __t.u16(),
  seat: __t.u8(),
  kind: __t.u8(),
  action: __t.u8(),
  legalMask: __t.u64(),
  fingerprint: __t.u64(),
  latencyMs: __t.u16(),
  engineCheatKind: __t.u8(),
  selfReportedCheat: __t.u8(),
});
export type DecisionInput = __Infer<typeof DecisionInput>;

export const Game = __t.object("Game", {
  id: __t.u64(),
  schemaVersion: __t.u8(),
  tournamentId: __t.option(__t.u64()),
  startedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  targetScore: __t.u16(),
  variant: __t.u8(),
  team1Seat0ModelId: __t.u32(),
  team1Seat2ModelId: __t.u32(),
  team2Seat1ModelId: __t.u32(),
  team2Seat3ModelId: __t.u32(),
  team1Score: __t.i16(),
  team2Score: __t.i16(),
  team1Bags: __t.u8(),
  team2Bags: __t.u8(),
  winnerTeam: __t.u8(),
  rngSeed: __t.u64(),
  allowRenege: __t.bool(),
  chatPolicy: __t.u8(),
  promptCheatingMode: __t.u8(),
  promptForDetection: __t.bool(),
  announceDetectedCheats: __t.bool(),
  agentDetectionQuorum: __t.bool(),
  cheatConsequenceKind: __t.u8(),
  cheatConsequenceValue: __t.i16(),
  spadesLeadPolicy: __t.u8(),
  minimumTeamBid: __t.u8(),
});
export type Game = __Infer<typeof Game>;

export const GameCompleteInput = __t.object("GameCompleteInput", {
  id: __t.u64(),
  team1Score: __t.i16(),
  team2Score: __t.i16(),
  team1Bags: __t.u8(),
  team2Bags: __t.u8(),
  winnerTeam: __t.u8(),
});
export type GameCompleteInput = __Infer<typeof GameCompleteInput>;

export const GameStartInput = __t.object("GameStartInput", {
  schemaVersion: __t.u8(),
  tournamentId: __t.option(__t.u64()),
  targetScore: __t.u16(),
  variant: __t.u8(),
  team1Seat0ModelId: __t.u32(),
  team1Seat2ModelId: __t.u32(),
  team2Seat1ModelId: __t.u32(),
  team2Seat3ModelId: __t.u32(),
  rngSeed: __t.u64(),
  allowRenege: __t.bool(),
  chatPolicy: __t.u8(),
  promptCheatingMode: __t.u8(),
  promptForDetection: __t.bool(),
  announceDetectedCheats: __t.bool(),
  agentDetectionQuorum: __t.bool(),
  cheatConsequenceKind: __t.u8(),
  cheatConsequenceValue: __t.i16(),
  spadesLeadPolicy: __t.u8(),
  minimumTeamBid: __t.u8(),
});
export type GameStartInput = __Infer<typeof GameStartInput>;

export const Hand = __t.object("Hand", {
  id: __t.u64(),
  gameId: __t.u64(),
  handNumber: __t.u8(),
  dealerSeat: __t.u8(),
  dealSeat0: __t.u64(),
  dealSeat1: __t.u64(),
  dealSeat2: __t.u64(),
  dealSeat3: __t.u64(),
  bidsPacked: __t.u32(),
  tricksWonPacked: __t.u16(),
  team1ScoreDelta: __t.i16(),
  team2ScoreDelta: __t.i16(),
});
export type Hand = __Infer<typeof Hand>;

export const HandRecordInput = __t.object("HandRecordInput", {
  gameId: __t.u64(),
  handNumber: __t.u8(),
  dealerSeat: __t.u8(),
  dealSeat0: __t.u64(),
  dealSeat1: __t.u64(),
  dealSeat2: __t.u64(),
  dealSeat3: __t.u64(),
  bidsPacked: __t.u32(),
  tricksWonPacked: __t.u16(),
  team1ScoreDelta: __t.i16(),
  team2ScoreDelta: __t.i16(),
});
export type HandRecordInput = __Infer<typeof HandRecordInput>;

export const Model = __t.object("Model", {
  id: __t.u32(),
  name: __t.string(),
  kind: __t.u8(),
  version: __t.string(),
  introducedAt: __t.timestamp(),
});
export type Model = __Infer<typeof Model>;

export const Reasoning = __t.object("Reasoning", {
  decisionId: __t.u64(),
  textZstd: __t.byteArray(),
});
export type Reasoning = __Infer<typeof Reasoning>;

export const Tournament = __t.object("Tournament", {
  id: __t.u64(),
  name: __t.string(),
  format: __t.u8(),
  startedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  championTeam: __t.option(__t.string()),
});
export type Tournament = __Infer<typeof Tournament>;

