// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteGameReducer from "../complete_game_reducer";
import CompleteTournamentReducer from "../complete_tournament_reducer";
import RecordAccusationReducer from "../record_accusation_reducer";
import RecordCommunicationReducer from "../record_communication_reducer";
import RecordCompleteGameReducer from "../record_complete_game_reducer";
import RecordDecisionReducer from "../record_decision_reducer";
import RecordHandReducer from "../record_hand_reducer";
import RecordReasoningReducer from "../record_reasoning_reducer";
import RegisterModelReducer from "../register_model_reducer";
import StartGameReducer from "../start_game_reducer";
import StartTournamentReducer from "../start_tournament_reducer";

export type CompleteGameParams = __Infer<typeof CompleteGameReducer>;
export type CompleteTournamentParams = __Infer<typeof CompleteTournamentReducer>;
export type RecordAccusationParams = __Infer<typeof RecordAccusationReducer>;
export type RecordCommunicationParams = __Infer<typeof RecordCommunicationReducer>;
export type RecordCompleteGameParams = __Infer<typeof RecordCompleteGameReducer>;
export type RecordDecisionParams = __Infer<typeof RecordDecisionReducer>;
export type RecordHandParams = __Infer<typeof RecordHandReducer>;
export type RecordReasoningParams = __Infer<typeof RecordReasoningReducer>;
export type RegisterModelParams = __Infer<typeof RegisterModelReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;
export type StartTournamentParams = __Infer<typeof StartTournamentReducer>;

